# Generated by Django 2.2.8 on 2019-12-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('newowner', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('itemtype', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('bidtype', models.CharField(max_length=100)),
                ('starting', models.IntegerField()),
                ('minbid', models.IntegerField()),
                ('image', models.IntegerField()),
                ('stopbid', models.IntegerField()),
                ('currentbid', models.IntegerField()),
                ('lastbidder', models.CharField(max_length=100)),
                ('decremented', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField()),
                ('verification_code', models.CharField(max_length=100)),
                ('balance', models.IntegerField()),
                ('reservedbalance', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
        ),
    ]
