# Generated by Django 2.2.8 on 2019-12-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0002_auto_20191220_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(blank=True)),
                ('verification_code', models.CharField(blank=True, max_length=100)),
                ('balance', models.IntegerField(blank=True)),
                ('reservedbalance', models.IntegerField(blank=True)),
                ('active', models.BooleanField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
