# Generated by Django 2.2.8 on 2019-12-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0005_remove_auctionuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='auctionuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='auctionuser',
            name='surname',
        ),
    ]
