# Generated by Django 2.2.8 on 2019-12-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0007_auto_20191220_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionuser',
            name='active',
        ),
        migrations.AlterField(
            model_name='item',
            name='bidtype',
            field=models.CharField(choices=[('I', 'Increment'), ('AI', 'Auto-Increment'), ('D', 'Decrement')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemtype',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='lastbidder',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='minbid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='newowner',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
