# Generated by Django 2.2.8 on 2019-12-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0009_auto_20191221_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('historytype', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('issold', models.BooleanField(default=False)),
                ('soldto', models.CharField(max_length=100)),
                ('bidder', models.CharField(max_length=100)),
                ('bidamount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('message', models.CharField(max_length=100)),
                ('isread', models.BooleanField(default=False)),
            ],
        ),
    ]
