# Generated by Django 2.2.8 on 2019-12-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0010_history_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='delta',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='period',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='stop',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
