# Generated by Django 2.2.8 on 2019-12-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0011_auto_20191221_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bidtype',
            field=models.CharField(choices=[('I', 'Increment'), ('II', 'Instant-Increment'), ('D', 'Decrement')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='delta',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='period',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='stop',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
